---
# file: roles/openldap/tasks/main.yml
- name: packages install
  yum: name={{item}} state=present
  with_items:
    - openldap-servers
    - openldap-clients

- name: ldap db config.
  template: src=DB_CONFIG.j2 dest=/var/lib/ldap/DB_CONFIG owner=ldap group=ldap

- name: ldap settings
  template: src=slapd.conf.j2 dest=/etc/openldap/slapd.conf owner=root group=root mode=644
  notify:
    - delete ldap default db
    - ldap create db
    - openldap start
    - openldap restart

- name: openldap start
  service: name=slapd state=started enabled=yes

- name: ldap rsyslogd
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.conf
  notify: rsyslog restart
